theme: jekyll-theme-cayman
name: Computational Biology and Artificial Intelligence
email: siuwengin@gmail.com
description: Computational Biology and Artificial Intelligence Group - Institute of Science and Environment - University of Saint Joseph
author:
  name: Shirley W. I. Siu
  twitter: ShirleyWISiu
  picture: images/shirleysiu.png
markdown: kramdown
