title: Computational Biology and Artificial Intelligence Group
logo: /images/logo.png
description: Institute of Science and Environment - University of Saint Joseph
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
